### ISSUE TITLE
Avvisi offline

### ISSUE THREAD

**Issue by PorfirioTramontana** [Tianhar/IngegneriaUniparthenope#1]
Gestire la fruizione di informazioni (ad es. avvisi) quando offline

**Comment by Tianhar** [comment]
Ho aggiunto la funzione che, una volta che il download è andato a buon fine e si accede alla sezione (News, docenti o personale), salva gli ArrayList relativi a quella sezione sulla memoria interna. Se all'apertura dell'applicazione non c'è connessione, allora i dati caricati saranno quelli dalla memoria se presenti.
