### ISSUE TITLE
Eccezioni mappe

### ISSUE THREAD

**Issue by PorfirioTramontana** [Tianhar/IngegneriaUniparthenope#2]
Gestire i casi eccezionali nell'utilizzo delle mappe

**Comment by colviem** [comment]
Ho aggiunto alla mappa la posizione corrente del dispositivo con il percorso per raggiungere la l'università. Con diversi if si gestiscono le varie eccezioni, dei toast informano l'utente riguardo i vari casi.  Aggiunto un bottone sulla mappa per aggiornare posizione e percorso. Il permesso di accedere alla posizione viene richiesto esplicitamente una tantum all'avvio dell'app (nel main) appena installata.
