### ISSUE TITLE
Applicazione Web

### ISSUE THREAD

**Issue by PorfirioTramontana** [Tianhar/IngegneriaUniparthenope#5]
Realizzazione di una applicazione Web con node.js che mette a disposizione alcune delle funzionalità dell'app o del sito di uniparthenope nel browser di un dispositivo mobile.

**Comment by colviem** [comment]
Applicazione web terminata, il codice è visibile all'interno della cartella App Web (nello stesso repository github), sito https://ingegneria-uniparthenope.herokuapp.com/
